/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class ArrayStatsTest {

    ArrayStats stats = new ArrayStats();
    int[] sample = {4, 1, 7, -2, 0};

    @Test
    public void testMinimumUsingForLoop() {
        assertEquals(-2, stats.minimumUsingForLoop(sample));
    }

    @Test
    public void testMaximumUsingForLoop() {
        assertEquals(7, stats.maximumUsingForLoop(sample));
    }

    @Test
    public void testSumUsingForLoop() {
        assertEquals(10, stats.sumUsingForLoop(sample));
    }

    @Test
    public void testAverageUsingForLoop() {
        assertEquals(2, stats.averageUsingForLoop(sample));
    }

    @Test
    public void testMinimumUsingStream() {
        assertEquals(-2, stats.minimumUsingStream(sample));
    }

    @Test
    public void testMaximumUsingStream() {
        assertEquals(7, stats.maximumUsingStream(sample));
    }

    @Test
    public void testSumUsingStream() {
        assertEquals(10, stats.sumUsingStream(sample));
    }

    @Test
    public void testAverageUsingStream() {
        assertEquals(2, stats.averageUsingStream(sample));
    }
}